# -*- coding: utf-8 -*-
"""Task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10ELHxDWqiBC1cpYJP8Xkg9CJlK09RAfz
"""

import cv2

# Load the image
img = cv2.imread("/content/Aesha.37.47.jpeg")

# Convert the image to grayscale
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Invert the grayscale image
inverted_gray_img = 255 - gray_img

# Apply Gaussian Blur
blurred_img = cv2.GaussianBlur(inverted_gray_img, (21, 21), 0)

# Invert the blurred image
inverted_blurred_img = 255 - blurred_img

# Create the pencil sketch image
pencil_sketch_img = cv2.divide(gray_img, inverted_blurred_img, scale=256.0)

# Save the pencil sketch image
cv2.imwrite("output_image.jpg", pencil_sketch_img)

from skimage import io
 
img = io.imread("/content/Aesha.37.47.jpeg")
io.imshow(img)

from skimage import io
 
img1 = io.imread("/content/output_image.jpg")
io.imshow(img1)



